#name, main, version and api are required
name: PureEntities
main: milk\pureentities\PureEntities
#remember version and api is string, don't write it like this: 1.0.0, or there will be an exception
version: "1.0"
api: ["3.0.0-ALPHA10"]

load: STARTUP
author: Leinne
description: Implement all MCBE entities
website: https://github.com/LeinneSW/PureEntities
commands: []