name: PureEntities
main: leinne\pureentities\PureEntities
version: 2.0.0
api: [4.0.0]

load: STARTUP
author: LeinneSW
description: Implement all MCBE entities
website: https://github.com/LeinneSW/PureEntities
commands: []